trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOPATH: '$(Agent.BuildDirectory)/gopath' # Go workspace path
  GOROOT: '$(Agent.BuildDirectory)' # Go installation path
  GOBIN:  '$(GOROOT_1_12_X64)/bin' # Go binaries path
  GOVERSION: '1.12.7'
  modulePath: '$(GOPATH)/src/github.com/zycrophat/ifpl' # Path to the module's code

steps:
- script: |
    # mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    ls -aR '$(modulePath)'
  displayName: 'Set up the Go workspace'

- bash: make dist-all
  workingDirectory: '$(modulePath)'
  displayName: 'Run make'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(modulePath)/build/dist'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    FlattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'distributions'
    publishLocation: 'Container'