trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOPATH: '$(Agent.BuildDirectory)/gopath' # Go workspace path
  GOROOT: '$(Agent.BuildDirectory)/go' # Go installation path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  modulePath: '$(GOPATH)/src/ifpl' # Path to the module's code

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    ls -aR '$(modulePath)'
  displayName: 'Set up the Go workspace'

- script: |
    wget "https://storage.googleapis.com/golang/go1.12.5.linux-amd64.tar.gz" --output-document "$(Agent.BuildDirectory)/go1.12.5.tar.gz"
    tar -C '$(Agent.BuildDirectory)' -xzf "$(Agent.BuildDirectory)/go1.12.5.tar.gz"
  displayName: 'Install Go 1.12'

- script: |
    go version
    echo '$(modulePath)'
    git describe --tags
    git describe --tags --always
  workingDirectory: '$(modulePath)'
  displayName: 'go print version'

- bash: make dist-all
  workingDirectory: '$(modulePath)'
  displayName: 'Run make'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(modulePath)/build/dist'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    FlattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'distributions'
    publishLocation: 'Container'